ALTER TABLE "RosterEntry"
ADD COLUMN "attendanceStatus" TEXT NOT NULL DEFAULT 'Not marked',
ADD COLUMN "actualStartTime" TEXT NOT NULL DEFAULT '',
ADD COLUMN "actualEndTime" TEXT NOT NULL DEFAULT '',
ADD COLUMN "plannedWorkingHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "workedHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "overtimeHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "attendanceNotes" TEXT NOT NULL DEFAULT '',
ADD COLUMN "markedBy" TEXT NOT NULL DEFAULT '',
ADD COLUMN "markedAt" TIMESTAMP(3);
